### ISSUE TITLE
Read parameters from proxied service metadata 

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#103]
The following parameters which are used by ```snet-daemon``` are present in service config:
- mpe_address 
- payment_address
- group_id
- price

```snet-daemon``` should load them from the same source as client do. 

This issue is to implement the following:
- ```snet-daemon``` reads registry on start and using proxied service name finds IPFS metadata hash.
- using the hash ```snet-daemon``` reads metadata from IPFS
- using endpoint as id (separate id can be added as well) daemon finds its instance in metadata and determines the group it belongs to
- then daemon reads parameters from metadata

Additional features:
- add option to load service metadata from file or IPFS for debug purposes
- move some parameters from daemon config to the metadata, like:
  - service_type
  - wire_encoding
  - daemon_type
  - payment_expiration_threshold

**Comment by anandrgit** [comment]
Was resolved through 
https://github.com/singnet/snet-daemon/pull/133

**Comment by astroseger** [comment]
This issue haven't been fully resolved.
There is no possibility to read metadata from the file.... 
@raamb should we reopen this issue or create another one?

**Comment by astroseger** [comment]
(of course we could decide that we don't need an option for reading metadata from the file.... But it makes system more flexible...)
