### ISSUE TITLE
Unexpected error after successful blockchain transaction

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#106]
This code: https://github.com/singnet/snet-daemon/blob/f76d78f1d23524bbfc14db1a9ece611df1561817/blockchain/escrow.go#L46-L49

Returns error despite transaction itself is committed to the blockchain successfully. PR https://github.com/singnet/snet-daemon/pull/105 is temporary fix. This is to fix it properly.

**Comment by anandrgit** [comment]
We can close this after the PR  https://github.com/singnet/snet-daemon/pull/184 is merged to the master 
As claim will now happen through snet-cli ( and no write operation on block chain from Daemon)
