### ISSUE TITLE
Daemon to read MPE configuration values from registry

### ISSUE THREAD

**Issue by raamb** [singnet/snet-daemon#111]

**Comment by vsbogd** [comment]
Seems to be a duplicate of https://github.com/singnet/snet-daemon/issues/103

**Comment by Dinesh2521** [comment]
We already started working on it

**Comment by astroseger** [comment]
Just in case there is example of metadata. Two payment groups (group1 group2), and two endpoints in each.
See also: https://github.com/singnet/wiki/blob/master/multiPartyEscrowContract/MPEServiceMetadata.md

"{\"version\": 1, \"display_name\": \"ExampleService\", \"encoding\": \"grcp\", \"service_type\": \"grcp\", \"payment_expiration_threshold\": 40320, \"model_ipfs_hash\": \"QmVPJ9KgvMRR28tH1p34TAuD5c5rveQ3DdstRTGTnoyzfJ\", \"mpe_address\": \"0x5c7a4290f6f8ff64c69eeffdfafc8644a4ec3a4e\", \"pricing\": {\"price_model\": \"fixed_price\", \"price\": 42}, \"groups\": [{\"group_name\": \"group1\", \"group_id\": \"T3O5AMW0AOTz5mnmFvvdpEO1eSDlA3hXVvdmRqKToXs=\", \"payment_address\": \"0x3b2b3C2e2E7C93db335E69D827F3CC4bC2A2A2cB\"}, {\"group_name\": \"group2\", \"group_id\": \"aC60qKLVOJzS/dstHvq1dyvti6Ql9+RLlDaD7/BY/sw=\", \"payment_address\": \"0x0067b427E299Eb2A4CBafc0B04C723F77c6d8a18\"}], \"endpoints\": [{\"group_name\": \"group1\", \"endpoint\": \"localhost:8080\"}, {\"group_name\": \"group1\", \"endpoint\": \"localhost:8081\"}, {\"group_name\": \"group2\", \"endpoint\": \"8.8.8.8:8083\"}, {\"group_name\": \"group2\", \"endpoint\": \"localhost:8081\"}]}"

**Comment by raamb** [comment]
Completed as part of #133
