### ISSUE TITLE
Authenticate etcd clients when connecting to etcd cluster

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#117]
At the moment there is no authentication when etcd client is connecting to etcd server. It is not a problem for the one daemon/one etcd node case. But it should be implemented for case of using etcd cluster over the network.

Another related issue is encryption of network traffic between the etcd client and etcd node.

**Comment by anandrgitnirman** [comment]
we now have a central etcd cluster set up and certificates are required to connect . Hence closign this issue 
https://github.com/singnet/snet-daemon/blob/master/etcddb/etcddb_client.go#L101-L121
