### ISSUE TITLE
Refactor service_metadata global struct

### ISSUE THREAD

**Issue by raamb** [singnet/snet-daemon#139]
Per Vitaly's suggestion - 
I would have service_metadata instance as a component instead of making global variable. It can be instantiated as a component in components.go and injected as dependency into all components which require it. It allows:

having dependency graph in explicit form in components.go; at the moment metadata is implicitly initialized in blockchain component and if there is a component which requires metadata but not requires blockchain it is not obvious that it should be initialized after blockchain;
passing custom formed objects as parameters of the components in unit tests instead of setting global settings;

**Comment by vsbogd** [comment]
Thanks @raamb. Adding link to original comment https://github.com/singnet/snet-daemon/pull/133#discussion_r234873115
