### ISSUE TITLE
Two similar properties: daemon_listening_port and daemon_end_point

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#141]
At the moment we have two properties to configure essentially same thing: ```daemon_listening_port``` and ```daemon_end_point``` (see https://github.com/singnet/snet-daemon/pull/140/files#r235508483). 

I can imaging setup where these two things are not the same but it can be surprising for users.

Don't have idea how to fix it properly so far. One of the options don't support such setups. This issue is to discuss it.

**Comment by anandrgit** [comment]
we derive the Daemon port from the Daemon end point ( there is no Daemon port in the config anymore)
