### ISSUE TITLE
Enhance Daemon init functionality to support different test networks

### ISSUE THREAD

**Issue by raamb** [singnet/snet-daemon#142]
Add an optional network flag to the snetd init command to generate config files with registry and mpe address pre-populated for the specified network. So behaviour is as follows

`snetd init`
Command above will generate config with address corresponding to local setup (currrent behaviour)

`snetd init kovan`
Command above will generate config with address corresponding to kovan test network

`snetd init mainnet`
Command above will generate config with address corresponding to main net 

Essentially a convenience feature for developers to get started easily. They will still have to update the config for other entries such as endpoint, orgname, servicename etc

**Comment by anandrgit** [comment]
@raamb 
The user just needs to specify which network to use through the config 
"blockchain_network_selected"="kovan"
Pull Request #190 , Daemon will auto determine the Registry address and the block chain end point , 
Do we still need this command line option in Daemon  ?
