### ISSUE TITLE
Call payment.CompleteAfterError() even if panic() happens

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#145]
See: 
https://github.com/singnet/snet-daemon/blob/82ae1ca8cf397b1335c866b136919d5f5ff49fa9/handler/interceptors.go#L109

This call should be deferred and called even when panic() happened  during handler call.

**Comment by raamb** [comment]
@stellarspot can we close this issue? Your PR #154 resolves this issue I believe.

**Comment by vsbogd** [comment]
@raamb , it is still not tested, no unit test and no manual test, I would close it after adding unit test.
