### ISSUE TITLE
Daemon end point format 

### ISSUE THREAD

**Issue by anandrgit** [singnet/snet-daemon#153]
Daemon end point is of  the form the "127.0.0.1:8080" or "localhost:8080" ( what is stored in the meta data)  we need to standardise on how to derive if it is  http or https

**Comment by vsbogd** [comment]
See https://github.com/singnet/snet-daemon/pull/150#discussion_r236979049 also, standard format of the URI will allow simplifying the code.

**Comment by raamb** [comment]
We need to enforce this on snet-cli then

**Comment by vsbogd** [comment]
@stellarspot suggested using host + port across all of the tools: ```snet-cli```, ```snet-daemon``` to get rid of confusion. Then internally we can keep endpoint as ```"<host>:<port>"``` but in ```snet-cli``` interface and ```snet-daemon``` configuration user should set <host> and <port> variables separately.

**Comment by raamb** [comment]
Same as #160.
The endpoint is going to be used by clients to connect to the daemon + service. 
My proposal is to make the endpoint a valid URI of the form <schema>://<host>:<port>
The port alone is optional and if not provided would default. We can enforce this in the snet-cli as well to error out if the provided URI is not in this format.

**Comment by raamb** [comment]
@vsbogd @stellarspot shall we standardize the format  as <schema>://<host>:<port> across daemon and client?

**Comment by vsbogd** [comment]
@raamb , I think it makes sense

**Comment by astroseger** [comment]
If scheme==https should user (snet-cli) use secure_channel instead of insecure_channel?

**Comment by vsbogd** [comment]
@astroseger , I think so, but I think it should be couple of separate issues on daemon and snet-cli

**Comment by anandrgit** [comment]
@astroseger 
Daemon support both formats currently
<schema>://<host>:<port> and <host>:<port>.

https://github.com/singnet/snet-daemon/blob/master/snetd/cmd/serve.go#L137-L157

We will let it support only the <schema>://<host>:<port> as the agreed format once this is enforced on the snet-cli side as well

**Comment by ferrouswheel** [comment]
I will make a change to my snet-cli PR to add `http://` to the endpoint in the interim. I think that as soon as we have a good workflow for ssl certificates we should make all the defaults `https://`.

**Comment by anandrgitnirman** [comment]
refer to  #202 and #199  
Daemon end point is now oblivious to what is there in service metadata , will close this issue once the PR is merged
