### ISSUE TITLE
metadata endpoint format

### ISSUE THREAD

**Issue by stellarspot** [singnet/snet-daemon#160]
Right now endpoint in the daemon config file is defined as host:port

People tends to add it as http://host:port which is now indicated as error.
See the corresponding issue https://github.com/singnet/snet-cli/issues/127 in snet-cli

It should be defined if it is correct to define endpoint with schema or not.

The better way can be to define host and port separately in the config file. 
Like daemon_endpoint_host and daemon_endpoint_port.

**Comment by stellarspot** [comment]
There is already DAEMON_LISTENING_PORT property in the snet-daemon config file.
Should this port be always the same as in DAEMON_END_POINT?

**Comment by stellarspot** [comment]
There are also other endpoint in the snet-daemon config file: ETHEREUM_JSON_RPC_ENDPOINT, PASSTHROUGH_ENDPOINT, IPFS_END_POINT.

DAEMON_END_POINT format should be consistent with these endpoints as well.

**Comment by vsbogd** [comment]
Seems to be dup of https://github.com/singnet/snet-daemon/issues/153

**Comment by stellarspot** [comment]
Closed as duplicate of #153
