### ISSUE TITLE
"--service_type process" services don't appear to be working

### ISSUE THREAD

**Issue by ramongduraes** [singnet/snet-daemon#169]
When reading the documentation we came across a way of calling a service as a "process" in which, instead of using json or grpc, the daemon would send inputs via stdin and return whatever the service writes to stdout. I've tried to implement that but failed.

I have created and published the service using "--service_type process" and specified the path of the python executable via "EXECUTABLE_PATH" in snetd config json file. I managed to get snet cli to communicate with the daemon (so the endpoint is correct) and the daemon was able to execute the service. It sends the call method defined in the .proto file as an argument (which I could print out to a log file) but the stdin itself gets lost somewhere along the way.

We're not sure if this is an issue with snet cli or snet daemon but we believe that snet cli waits for the user to finish writing to stdin to then send everything as an argument to the daemon, which apparently expects cli's stdin. So the solution would be to agree on either sending the user's input as an argument or properly connecting cli's stdin all the way to the service's stdin (and make sure its stdout makes its way back to the client). It'd be awesome from a service's point of view if the second were to be implemented (it would allow for chatbots and streaming services in general to be easily integrated)!

**Comment by vsbogd** [comment]
In current design there is another way of implementing chatbots use case you have mentioned. Service publisher can provide [bidirectional streaming gRPC API](https://grpc.io/docs/tutorials/basic/python.html#bidirectional-streaming-rpc) and then client can use it to implement chatting functionality. But gRPC streaming is not supported by ```snet-cli``` at the moment.

**Comment by vsbogd** [comment]
What is the service you are trying to implement?

**Comment by ramongduraes** [comment]
Hey @vsbogd , thanks for the reply! 

So, about the service, it's supposed to be only an example of a service of type "process". I'm simply trying to get it to work for now but it consists of only the "add" method you mentioned before.

`
if __name__ == "__main__":

    log.debug("Running service.")
    method = sys.argv[1]
    log.debug("RECEIVED - Method: {}".format(method))

    if method == "add":
        log.debug("Method recognized.")
        with sys.stdin:
            for line in sys.stdin:
                log.debug("RECEIVED - Stdin: {}".formatline)
                if 'exit' in line:
                    log.debug("Exiting...")
                    exit(0)
                else:
                    log.debug("Receiving: {}".format(line))
`

**Comment by ramongduraes** [comment]
Accidentally closed the issue, sorry

**Comment by vsbogd** [comment]
Hm, ok if the call above with command line parameters doesn't reach the target executable it is strange, I will look at it.

**Comment by ramongduraes** [comment]
Hey @vsbogd thanks a lot for the support! I hadn't changed the default encoding when publishing the service, so that was the problem indeed. I'll make a short tutorial on how to publish process type services and add it to the wiki.

**Comment by ferrouswheel** [comment]
@vsbogd I think if we are supporting process-based calls, we should implement an encoding option of "raw". Which allows the user to specify the raw character input to stdin. Forcing json encoding slightly defeats the purpose of letting us pass raw data to a program.

However, I'm not sure how to define such a "raw" encoding via protobuf. Perhaps we could just specify that the protobuf definition of a service needs it's request and response messages to have a "stdin" and a "stdout" field?

(I don't think this is necessary for the beta, but we should revisit it eventually)

**Comment by vsbogd** [comment]
@joel Do you mean that client sends string to the service and gets a string as response? You can described it as 
```protobuf
message Request{ string input = 1; }
message Response{ string output = 1; }
```
Do you mean that daemon should have a way of encoding when it just passes input to the stdin and fills output from stdout?

I think that cases when the only data which needed to be passed forth and back is text string are rare. But on the other hand using JSON in such case is not so difficult. And supporting such use-case opens easy way for people to create unstructured APIs.

**Comment by vsbogd** [comment]
I don't see a big difference between processing the end of line and looking for the end of a JSON structure. Yes first is much simpler, but using JSON library I think the second is not a problem as well. 

Translation like example, I mean converting text to text the only example I can see. But should we have some specific encoding type for text to text converting console applications only?

**Comment by ferrouswheel** [comment]
In a JSON structure you have to receive the entire structure before you can check it's valid, or to check if you have all the required keys (since the keys in JSON objects have no order). with raw stdin/stdout, there is an explicit ordering to the data. You can send any preamble first, and then stream the rest of the data. At the same time, the process can be streaming the results to stdout. JSON makes this hard (I'm sure we could make something work, but it'd be a hack), protobuf supports this but is a binary format.

I think if we are going to require JSON (or protobuf), we should also require an actual rpc service. If people are forced to write/include JSON/protobuf processing code, they can include a RPC server too.

I think forcing a serialization format also bugs me because it breaks the unix philosophy of command line programs. If someone has a great machine learning executable that processes stdin and returns results on stdout, we are telling them they need to wrap json around it instead of making it easy for them to deploy their executable on SNet.

**Comment by vsbogd** [comment]
> At the same time, the process can be streaming the results to stdout. JSON makes this hard (I'm sure we could make something work, but it'd be a hack), protobuf supports this but is a binary format.

gRPC supports it by sending many small but well formed data messages (in JSON or protobuf depends on encoding type) but not by streaming the sequence of symbols. It is the reason why I think the suggested protocol cannot be naturally implemented using gRPC. 

The only solution I can see should work by the following way: when daemon receives gRPC stream, it starts console application and then keeps stdin and stdout streams till stream is closed by client. Then daemon starts copying each message to the stdin. And at the same time it should get data from stdout and somehow form response gRPC messages from it. The question is how does daemon know that message it recieved from stdout is complete? One of the ways is to get just all data which is in the buffer right now and send it back.

Is it similar to your vision?

**Comment by ferrouswheel** [comment]
> The question is how does daemon know that message it recieved from stdout is complete

I think it should work like most standard libraries. stdin/stdout are buffered, but a newline clears the buffer. gRPC should send data on the stream in the same way, either when the buffer is full or when a newline is encountered. The entire gRPC call is completed when the process exits and closes stdin/stdout.

**Comment by vsbogd** [comment]
I agree, that it can be implemented by this way. We may point in documentation that "process" kind of services uses some standard gRPC API, like:
```proto
message Input {
  string data = 1;
}
```
or 
```proto
message Input {
  repeated byte data = 1;
}
```
And implement the logic above in the daemon for `process` type of service.
