### ISSUE TITLE
Provide an interface for unlocking channels after application crash.

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#173]
Daemon may fail to cleanup state correctly in case it crashes. If there are any transactions were in progress at this moment they will stay locked, see https://github.com/singnet/snet-daemon/issues/172. So we probably need some management interface to deal with, see https://github.com/singnet/snet-daemon/issues/172#issuecomment-446765579

Before we have it in place we need to document manual resolution procedure.

**Comment by vsbogd** [comment]
> should we unlock the channel when the daemon is starting up?

We cannot unlock channels on daemon start as there are may be more then one instance of daemon, in such case unlock logic will be broken.

Ideally I would say this functionality should be a part of "Operator UI" described in issue #29. What kind of UI should it be it is another question which is better to discuss in #29. I had experience of using Java JMX to add web interfaces to the service processes to review and manipulate by process internal state directly via HTTP. It is very powerful tools which can help to solve many complex things quickly.

Taking into account time restrictions for Beta, I would add additional command line interface, because it is straightforward thing. And then move this functionality to the "Operator UI" when issue #29 is implemented.

**Comment by Dinesh2521** [comment]
@vsbogd 
need help with few clarifications
1. Can we assume that the user already knows the channel ID to Unlock? or we should give an option to show the locked channel IDs?
2. How many locked channels we will have? only one or it could be more?

planning to add new command group for channel related commands
example command to unlock a channel would be : **snetd channel --unlock <channelID>**
we can keep add other channel related commands as need

**Comment by vsbogd** [comment]
> Can we assume that the user already knows the channel ID to Unlock? or we should give an option to show the locked channel IDs?

Yes, we can assume user should already know channel ID to unlock, because there are many ID can be locked simultaneously and it manual investigation is required to find out improperly locked id. One need to check that there are no operation on this channel is in progress using daemon logs for instance (see issue #172).

> How many locked channels we will have? only one or it could be more?

Is your question about do we need to support unlock for many channels in one command? The answer depends on daemon usage profile. I would say it should be a rare situation so for now we can have command to unlock one channel and use bash script to unlock many channels if it is needed.

**Comment by Dinesh2521** [comment]
We will be removing the key from etcd to unlock the channels.
unlock command would look like 
`$ sned channel --unlock {channel ID}`

**Comment by raamb** [comment]
PR #187 resolves this issue.
