### ISSUE TITLE
Take Registry address from platform-contracts by default.

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-daemon#175]
Daemon should take Registry address from platform-contracts by defaults.

Registry address is already here: resources/blockchain/node_modules/singularitynet-platform-contracts/networks. This file contains dictionary: netowrkID -> "contract addresses" 
1. At compilation time: we should take networks and store than as a constant
2. At execution time we should take networkId from RPC endpoint, ans use stored contract addresses by default.

**Comment by vsbogd** [comment]
related to #142
