### ISSUE TITLE
snet-daemon throws an error for grpc messages greater than 4MB

### ISSUE THREAD

**Issue by Habush** [singnet/snet-daemon#185]
I am getting **ResourceExhausted** error from _snet-daemon_ when trying to send a grpc message greater than 4MB to a service . This is due to grpc default limit and I have removed that limit in my service and the service works with any message size, however, the daemon still complains and doesn’t proxy the request from the client. Is there a way to remove the file size limit on the snet-daemon?
The daemon throws the following error:

> error="rpc error: code = Internal desc = failed proxying s2c: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (10432043 vs. 4194304)"

**Comment by ferrouswheel** [comment]
We should encourage the use of streaming requests and make the max message size a config key. We should require everyone to accept 4GB messages.

Has there been any assessment as to whether increasing the max message size impacts memory use?

If public APIs can be sent 4GB messages, and those messages are pre-allocated before being verified as a correct user, then it'd be pretty easy for a malicious actor to take down SNet services.

**Comment by anandrgit** [comment]
Created a new issue to track the comments from @ferrouswheel 
#195
