### ISSUE TITLE
Allow using same ETCD storage for different services

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#188]
In order to allow storing data for different services in same ETCD storage we need to add unique prefix for each service's keys. 

Proposed prefix includes:
- organization id
- service id
- network id or registry contract id

Performance cost of having longer keys needs to be investigated.

Simplest way to implement it is to wrap `atomicStorage` to the `PrefixedAtomicStorage` with prefix proposed, see: https://github.com/singnet/snet-daemon/blob/05b4021d74e0516191289d3b95f68d1f94132385/snetd/cmd/components.go#L144-L156 and https://github.com/singnet/snet-daemon/blob/05b4021d74e0516191289d3b95f68d1f94132385/escrow/atomic_storage.go#L31

**Comment by astroseger** [comment]
Actually MPE_address is enough for prefix. channel_id is already implicitly include organization_id and service_id (via group_id).
So I propose to use MPE_address as a prefix. It is enough.

**Comment by vsbogd** [comment]
> So I propose to use MPE_address as a prefix. It is enough.

Storage has more complex keys than `channel_id`. This issue is about has independent namespaces of the keys for different applications, so prefix should reflect application id.

**Comment by astroseger** [comment]
@vsbogd 
Do you mean that there are some keys which do not contains channel_id? 
If it is true then we probably should use group_id as application_id.

**Comment by vsbogd** [comment]
@astroseger, may be there are no such keys right now, but why we should expect that there will not be such cases in future. In order to understand that such solution is correct one need to keep in mind many different low level design details. 

I don't like idea of coupling service specific prefix with channel id. channel_id could be not unique among different services.

**Comment by anandrgitnirman** [comment]
With Single channel re use ( per Organization/per Group) the current key storage shoudl be good, we intend to add the network type ( ropsten/kovan/mainnet) as prefix to the key .With the same etcd cluster being used by all services now, we also wanted to give some authentaticaion  , seprate users will be created for each network and access to the respective keys with the env prefix will be given
