### ISSUE TITLE
Providing the service health/status

### ISSUE THREAD

**Issue by glautervl** [singnet/snet-daemon#203]
It would be useful if the daemon could provide the service health/status from CLI calls.

**Comment by ferrouswheel** [comment]
Dependency of singnet/snet-cli#193.

Would also be required to test service status from dapp.

**Comment by anandrgitnirman** [comment]
Could you have a look at the documentation at  [daemon heartbeat](https://github.com/singnet/snet-daemon/tree/master/metrics#heartbeat)

**Comment by astroseger** [comment]
So we should support it in snet-cli...

**Comment by glautervl** [comment]
Thanks, @anandrgitnirman.
