### ISSUE TITLE
Using go generate + compiling the proto files in the same folder 

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-daemon#205]
the generated files have the same file descriptor at times
for now this is addressed by manually by the below command 
protoc -I . ./*.proto --go_out=plugins=grpc:.

**Comment by anandrgitnirman** [comment]
hi @vsbogd , listed the steps below 

1)  ./scripts/install 
2)  check the auto files generated state_service.pb.go and control_servcie.pb.go
they both have the below file description genrated
**var fileDescriptor0** = []byte{

This is a problem as you cannot have two variables with the exact same name in the same folder 

this was resolved by running the command below while building the binaries.
protoc -I . ./*.proto --go_out=plugins=grpc:.

I am Looking at avoiding run this separately and use the //go generate ... 
itself to handle this.

**Comment by vsbogd** [comment]
How does CircleCI build this right now?

**Comment by anandrgitnirman** [comment]
[Circle CI](https://circleci.com/gh/singnet/snet-daemon/284) , seems to go fine , it does the below , need to dig more to see  why this never broke in Circle CI.
      - run:
          name: Run install script
          command: ./scripts/install
      - run:
          name: Run build script
          command: ./scripts/build linux amd64

however if you run this manually it breaks , we did have this issue while building the binary for the Daemon to be released and solved it by adding this``` protoc -I . ./*.proto --go_out=plugins=grpc:.```
