### ISSUE TITLE
snetd gets stuck warning of "another transaction on channel"

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-daemon#210]
While testing some serialization on the snet-cli side, I managed to put the server in this state:

```
time="2019-02-04T00:58:06Z" level=warning msg="gRPC handler returned error"
     error="rpc error: code = FailedPrecondition desc = another transaction on channel: {ID: 914} is in progress"
```

I thought it might time out eventually, but waiting for 15 minutes doesn't fix it. I'm unsure how to recover?

The daemon should ideally be robust to client failures. Even if it terminates the request before sending anything, the daemon should revert the transaction so a new one can be made.

**Comment by ferrouswheel** [comment]
#187 provides a way to unlock.

I still think the daemon should take care of unlocking if a client crashes. The client shouldn't be able to lock a channel permanently, or if we do allow this then the client should also have the power to unlock the channel somehow.

**Comment by vsbogd** [comment]
Hi @ferrouswheel ,

Most probable root cause is issue https://github.com/singnet/snet-daemon/issues/209. As daemon cannot handle singnals properly at the moment, killing daemon during transaction will leave channel in locked state.

Please use `sned channel --unlock {channel ID}` to unlock the channel (see issue https://github.com/singnet/snet-daemon/issues/173)

**Comment by vsbogd** [comment]
> I still think the daemon should take care of unlocking if a client crashes.

It cannot be done fully automatically, because channel can be locked by another daemon which works in parallel in multi replicas setup.

**Comment by ferrouswheel** [comment]
Ok, the issue I'm having is that I can reliably make snetd get into this state by using `snet client call`. snetd doesn't crash and there are no errors in the logs.

I have sent you the logs in slack as I'm not sure if any of the details should be considered secret.

**Comment by vsbogd** [comment]
As far as I see from this log, you have received the error because you have sent two requests at same second:
- time="2019-02-05T02:32:28Z" level=debug msg="New gRPC call received
- time="2019-02-05T02:32:28Z" level=debug msg="New gRPC call received"
and second request tried to lock channel while first was in progress.

As logs ends at the same second "time="2019-02-05T02:32:28Z" level=debug msg="Metrics posted successfully with status code : 200 "" it is unclear from your description + log:
-  Was first request finished successfully or not?
-  Have you tried to send request again after first request is finished?

Without answers it looks like normal behavior, at the moment daemon cannot handle two requests on the same channel in parallel, but it should be able handle them one by one.

**Comment by vsbogd** [comment]
raised PR to add nanoseconds to the timestamps https://github.com/singnet/snet-daemon/pull/213

**Comment by ferrouswheel** [comment]
Ok, I'm only making one call with snet-cli...

Doesn't the client need to make an initial grpc call to get channel state?

**Comment by vsbogd** [comment]
Yes, snet-cli does additional call to get channel state but this call doesn't block channel (I will double check it). Anyway the log you sent contains 3 calls: getting state and two requests, so probably we should look at snet-cli side.

**Comment by ferrouswheel** [comment]
I have stepped through the snet-cli code, and snetd doesn't log multiple calls until the snet-cli is already inside the grpc specific code.

Trying another service, I don't have this issue. However it did highlight that the snetd log for the failure had a line starting with "New payment received", but with `AuthorizedAmount: 0, Signature:` at the end.

Compare this with the successful service showed a non-zero authorized amount and non-null signature.

One thing that is different is that the failing service uses nested protobuf message types. So I wonder if that could somehow impact signature generation.

This doesn't really explain the duplicate request unless we have some automatic retry configured that I don't know about.

**Comment by ferrouswheel** [comment]
So far I have tried:
- deleting the etcd database and starting the snetd instance fresh
- creating and using a completely new channel
- extending the expiry block and adding extra AGI to a channel

I always get `AuthorizedAmount: 0` and an empty signature from snetd inside the payment object.

@astroseger Do you have any idea if the snet-cli could somehow send two grpc requests, or cause the authorized amount to be 0?

I don't know the MPE details well enough to have any further guesses for what's going on. :thinking:

**Comment by ferrouswheel** [comment]
The cause of this was due to the snetd.config file having the same passthrough endpoint/port. The snetd was proxying the request to itself! (thanks @arturgontijo for discovering my error) I will create an issue for a check to prevent the daemon doing this, but hopefully if someone googles this error they will find this issue and it will prompt them to check their config ;-)

```
# cat services/__init__.py 
registry = {
    'mask_rcnn_server': {
        'grpc': 6006,
        'jsonrpc': 6106,
        'snetd': 6206,
    },
}
# cat snetd.config.json 
{
   "DAEMON_END_POINT": "0.0.0.0:6206",
   "ETHEREUM_JSON_RPC_ENDPOINT": "https://kovan.infura.io",
   "IPFS_END_POINT": "http://ipfs.singularitynet.io:80",
   "REGISTRY_ADDRESS_KEY": "0xe331bf20044a5b24c1a744abc90c1fd711d2c08d",
   "PASSTHROUGH_ENABLED": true,
   "PASSTHROUGH_ENDPOINT": "http://127.0.0.1:6206", <<<<< should have been 6006
   "ORGANIZATION_ID": "snet",
   "SERVICE_ID": "semantic-segmentation",
   "LOG": {
       "LEVEL": "debug",
       "OUTPUT": {
            "TYPE": "stdout"
           }
   }
}
```
