### ISSUE TITLE
Fully implement "stateless" logic

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-daemon#220]
We should modify ```state_service``` in order to full implement state-less logic described here: https://github.com/singnet/dev-portal/blob/master/docs/concepts/mpe-stateless-client.md

**Comment by astroseger** [comment]
I've removed my initial proposition of simplified state_service because it was obviously wrong, so we should implement which is written in https://github.com/singnet/dev-portal/blob/master/docs/all/mpe/mpe-stateless-client.md

so simple add two new fields:
- oldnonce_signed_amount  last amount which was signed by client with nonce=current_nonce - 1.
- oldnonce_signature - last signature sent by client with nonce = current_nonce - 1. 

it is still very simple...

**Comment by astroseger** [comment]
@raamb 
Can we prioritize this issue? We cannot make SDK without it.

**Comment by astroseger** [comment]
@Dinesh2521 
I would also propose to change authorization strategy, similar to ```control_service``` (include block_number in the message to sign).

**Comment by astroseger** [comment]
There are two issues with the current implementation (#232):
1. It is not backward compatible, and as I believe is possible to do it backward compatible 
2. If ```current_signed_amount``` is 0 then daemon doesn't send ```old_nonce_signed_amount``` even if it is not 0.

It should be noted that we need ```old_nonce_signed_amount``` field **only** when last payment hasn't been claimed in the MPE contract (channel_nonce != block_chain_nonce). Daemon removes payments from the payment storage after it verify that nonce in blockchain has been updated.

It means that we could take ```old_nonce_signed_amount``` directly from payment storage. If there is no payment in payment storage for the given channel_id then we shouldn't send ```old_nonce_signed_amount``` (because we know that client will not need it anyway).

**Comment by vsbogd** [comment]
Taking into account data incompatibility, I would propose to revert last PR and rethink implementation, @Dinesh2521, @raamb  , what do you think?

**Comment by raamb** [comment]
I agree. @Dinesh2521 please revert this PR from main. Once the fixes have been made we can create a new PR
