### ISSUE TITLE
Remove redundant  logging from Daemon 

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-daemon#235]
time="2019-03-22T10:48:15.605729664Z" level=info msg="Service http://demo3208027.mockable.io/heartbeat status : {\"serviceID\":\"SERVICE001\", \"status\":\"SERVING\"}"

**Comment by anandrgitnirman** [comment]
@arturgontijo ,created an issue to clean this up , thanks for reporting

**Comment by vsbogd** [comment]
I would vote for changing level to debug instead.
