### ISSUE TITLE
Quieten heartbeat logging

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/snet-daemon#245]
My services are full of messages like:

```
time="2019-04-04T18:20:25.860239857Z" level=info msg="response received : [123 34 115 101 ... 125]"
time="2019-04-04T18:20:25.860292366Z" level=info msg="Service http://demo3208027.mockable.io/heartbeat status : {\"serviceID\":\"SERVICE001\", \"status\":\"SERVING\"}"
```

This makes it hard to find actual service activity.

It'd be nice to move these messages to debug level logs.

**Comment by anandrgitnirman** [comment]
hello @ferrouswheel , we had fixed this and have this resolved with issue https://github.com/singnet/snet-daemon/issues/235 below and PR https://github.com/singnet/snet-daemon/pull/236

**Comment by ferrouswheel** [comment]
Ah sorry, I didn't see that issue. Thanks :-)
