### ISSUE TITLE
Authentication in control_service.StartClaim seems to be disabled

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-daemon#247]
It seems that in control_service.StartClaim we do not check that block number is correct.

**Comment by anandrgitnirman** [comment]
the proto definition for control_service.proto does not have a place holder to pass the block number for StartClaimRequest , happy to add   uint64 current_block to this and ( we just need to call the current block number check ) 


message StartClaimRequest {
    //address of MultiPartyEscrow contract
    string mpe_address = 1;
    //channel_id contains id of the channel which state is requested.
    bytes channel_id = 2;
    //signature of the following message ("__start_claim", mpe_address, channel_id, channel_nonce)
    bytes signature = 3;
   //current block number 
    uint64 current_block = 4;
}
also , please note , all Daemon  protos are now present in the  artifact  
[snet-daemon-v0.1.10-linux-amd64.tar.gz](snet-daemon-v0.1.10-linux-amd64.tar.gz
) under the folder proto

**Comment by astroseger** [comment]
@anandrgitnirman 
Sorry for confusion. You don't need block_number in start_claim request, because we have channel_nonce. So this authentication can be used only once in any case.

It is actually written in protofile 
```
//signature of the following message ("__start_claim", mpe_address, channel_id, channel_nonce)
```

But do you check that this signature is valid?

**Comment by astroseger** [comment]
Ok. Seems you do check.. Sorry :)
