### ISSUE TITLE
Remove the constraint on having a service_metadata file when Blockchain calls are disabled

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-daemon#258]
In the current scenario , when block chain calls are disabled, Daemon still expects a mandatory service_metadata file to read, this ticket is to remove this hard dependency

**Comment by raamb** [comment]
When daemon is started with blockchain disabled it needs to be provided a service metadata file. If the metadata file is not provided daemon will not start up. PR #260 improves the messaging so its clear for service developer on what needs to be done
