### ISSUE TITLE
cannot read file resources/blockchain_network_config.json

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-daemon#274]
I failed to run the last version of daemon from the box.
It gives the following error 
```
Unable to initialize daemon                   error="cannot read the file resources/blockchain_network_config.json , error is could not read file: resources/blockchain_network_config.json: open ../resources/blockchain_network_config.json: no such file or directory"
```

I was able to solve this problem by linking resources folder from daemon source code folder into current directory which is not very intuitive.

**Comment by vsbogd** [comment]
@anandrgitnirman , is there any change to close this?

**Comment by anandrgitnirman** [comment]
@vsbogd 
Was fixed with https://github.com/singnet/snet-daemon/issues/280
