### ISSUE TITLE
Unit test results are always GREEN despite test failure

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#289]
Looks like `grep` call hides results of the tests:

https://github.com/singnet/snet-daemon/blob/d961ebaeeec5059eead6050d106f20c10ab913a2/scripts/test#L13-L22

**Comment by anandrgitnirman** [comment]
@vsbogd , seems the issue is not on the grep but more on the echo used at the line
```sh
then **echo** `GOCACHE=off go test -v ./${d: 0:-1} -coverprofile ${d: 0:-1}.part`;fi 
```
@prashantramangupta will raise a PR, I have tested this as well and able to see failed build after this fix

**Comment by anandrgitnirman** [comment]
reverted back the changes for now ( we will revisit the coverage piece again soon) , we have multiple PR coming up this week and early next week , hence the revert
