### ISSUE TITLE
Remove autogenerated files from test coverage

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#305]
This is to exclude from coverage autogenerated files like [control_service.pb.go](https://coveralls.io/builds/24196917/source?filename=escrow/control_service.pb.go)  as they negatively affect coverage ratio.

See also discussion here https://github.com/singnet/snet-daemon/pull/302#issuecomment-505898234

**Comment by anandrgitnirman** [comment]
this is fixed and code covergae refects the same
