### ISSUE TITLE
Processing parallel calls using different nonces

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#307]
One can use payments with different nonces to handle parallel calls using the same channel in daemon. In such case each thread or process use separate nonce and daemon checks that:
- it has payments for whole sequence of nonces from <blockchain nonce> to highest nonce used in payments;
- sum of amounts for payments with different nonces doesn't exceed amount of the channel;

Algorithm contains three parts:
- initialization:
-- client process requests daemon to reserve nonce;
-- daemon check that it has payment for internal latest nonce;
-- daemon increments internal latest nonce and returns previous nonce to the client;
-- client sends zero amount payment to confirm it reserved the nonce;
- call:
-- some client uses nonce it received from master client to make payments as usual;
-- daemon checks that for received payment it has payments for all nonces from blockchain one to received one in storage;
-- daemon checks that sum of payments amount doesn't exceed amount of the channel;
- claim:
-- daemin calls claim method of the MPE using latest payment for each nonce in increasing nonce order.

Sequence diagram (initialization part has two examples: (1) client1 requests nonce (2) client2 requests nonce; both examples are equivalent and provided only for the sake of completeness):
![sequence diagram](https://www.plantuml.com/plantuml/svg/pLLHIyCm47xFhpZwr86wfKE4uMGmVHI6ujjWnFIsHTga9EdGVs-wfDhEEbT1yAMKk-ykt_VTfPqPoxGjyumGAso643qP8JUGYlKQDKeBKacE9YAaS431HS5SS9u9bwF034J-7HPQEPm16dKWaovaqaRUCioLR8KUKUzGjqBtYpj2DbgL1JoWgVAU8N49EBy9NM026xGhNkfAmsgFY0Sm7CA8a9fy4wrzhnf96BTYnopMh0AmMSACAx6mPOv2mTxoIjfQQMWTsbKe9DUO7_1gLKrfewwcE_52fwDE0O51731dm79LIZiT3KYAXsf8FPL_R47onOBammBQAQ1j0Jrk0SgqtgCvox9U3SSdcUCK1NzCcSUXruLlCO3hAV0janAp45hAW1vNEKgNyhD1qs2pTzZVId1pRgwAlo_kREuahNAqMvMwINOPwQPTA6cmmve-wvNqsPDBhwnonY02UrOx_4EPz1IPfqtygezCclnQvpUZUa5kusZkzoLm0dpbY2ccqK_hdJ6HDnfN7qfdNHMDZuprb8BMbTWVENDFzpTv1m00)

[Sequence diagram source code](https://www.planttext.com/?text=pLLHIyCm47xFhpZwr86wfKE4uMGmVHI6ujjWnFIsHTga9EdGVs-wfDhEEbT1yAMKk-ykt_VTfPqPoxGjyumGAso643qP8JUGYlKQDKeBKacE9YAaS431HS5SS9u9bwF034J-7HPQEPm16dKWaovaqaRUCioLR8KUKUzGjqBtYpj2DbgL1JoWgVAU8N49EBy9NM026xGhNkfAmsgFY0Sm7CA8a9fy4wrzhnf96BTYnopMh0AmMSACAx6mPOv2mTxoIjfQQMWTsbKe9DUO7_1gLKrfewwcE_52fwDE0O51731dm79LIZiT3KYAXsf8FPL_R47onOBammBQAQ1j0Jrk0SgqtgCvox9U3SSdcUCK1NzCcSUXruLlCO3hAV0janAp45hAW1vNEKgNyhD1qs2pTzZVId1pRgwAlo_kREuahNAqMvMwINOPwQPTA6cmmve-wvNqsPDBhwnonY02UrOx_4EPz1IPfqtygezCclnQvpUZUa5kusZkzoLm0dpbY2ccqK_hdJ6HDnfN7qfdNHMDZuprb8BMbTWVENDFzpTv1m00)

**Comment by vsbogd** [comment]
Pros of this approach:
(+) changes in contracts are not required;
(+) payment signing process is almost not changed on client side.

Not solved issues:
(-) concurrency between clients which are connected to different daemon groups (in different regions for example) is still a problem.

**Comment by vsbogd** [comment]
Algorithm could be simplified and used without need of master client node

Then initialization part looks:
- initialization:
-- client process requests daemon to reserve nonce;
-- daemon increments internal latest nonce and returns previous nonce to the client;
-- client sends zero amount payment to confirm it reserved the nonce.

Sequence diagram:
![Sequence diagram](https://www.plantuml.com/plantuml/svg/jLJHIiCm57tFLrpwr86wfKC4SJAOFWgY-3OOCRtR8crIadJettkxfjfgdPtWIsblJaxEkUSsS-U5zMMUCUQLpn2Y9wVq1bArNgD5xK4RBT55Z1K4L58LWegBJD4Q1-4Wgj_XtXh2EU1H3pBfGoPTv8t0tEXEwH7j3csdT7T_ozZ6chA01tJLEWYTabxdhNekFGR1Z81mUXrOuH8sw5Uoj9MdrHuIZs0yXWbZZPassjRS3P89wTLE47jG6O3jBKfBY_aNUesluNl6MvkQ8ozhjRD9huX2l5LySS2SWCXDgVriCc8fVbN4cax_iutacutammRl5T6rmG_RG9qs-Iv4bXr5E1raaEm8HstnuCey3bndDSK8hcOWjq9hp49fgGDwMgrnljIV15j1unSO7AoD3SC7b5KxxdgEwMn9bbOv-gr9AOs-Hb9YXT4EUrfpp8WaWreHR9pNpghEEAJ_wTdiy1zjyY4sXoL-SOnDdlpPvmzHlQ3qSRIevoLe0doLY2ccqM_ZdGcLjuYh2ujQLrNZ0x4EsT3v9VP7pkb9j_mx)
[Sequence diagram source code](https://www.planttext.com/?text=jLJHIiCm57tFLrpwr86wfKC4SJAOFWgY-3OOCRtR8crIadJettkxfjfgdPtWIsblJaxEkUSsS-U5zMMUCUQLpn2Y9wVq1bArNgD5xK4RBT55Z1K4L58LWegBJD4Q1-4Wgj_XtXh2EU1H3pBfGoPTv8t0tEXEwH7j3csdT7T_ozZ6chA01tJLEWYTabxdhNekFGR1Z81mUXrOuH8sw5Uoj9MdrHuIZs0yXWbZZPassjRS3P89wTLE47jG6O3jBKfBY_aNUesluNl6MvkQ8ozhjRD9huX2l5LySS2SWCXDgVriCc8fVbN4cax_iutacutammRl5T6rmG_RG9qs-Iv4bXr5E1raaEm8HstnuCey3bndDSK8hcOWjq9hp49fgGDwMgrnljIV15j1unSO7AoD3SC7b5KxxdgEwMn9bbOv-gr9AOs-Hb9YXT4EUrfpp8WaWreHR9pNpghEEAJ_wTdiy1zjyY4sXoL-SOnDdlpPvmzHlQ3qSRIevoLe0doLY2ccqM_ZdGcLjuYh2ujQLrNZ0x4EsT3v9VP7pkb9j_mx)

**Comment by anandrgitnirman** [comment]
@vsbogd , since we have a working version of concurrecny already released and used in a live case by Eyob, can we close this ?
