### ISSUE TITLE
Typo at config.go

### ISSUE THREAD

**Issue by arturgontijo** [singnet/snet-daemon#398]
Hi guys, in order to update all the services deployment that I manage, I need this to be fixed:

`payent_***` -> `payment_***` ([config.go#L46-L48](https://github.com/singnet/snet-daemon/blob/master/config/config.go#L46-L48))

**Comment by arturgontijo** [comment]
Thanks, @anandrgitnirman!

I've made this hacky bandaid to keep my workflow going until then.

[config.go#L47-L52](https://github.com/arturgontijo/snet-daemon/blob/config/config/config.go#L47-L52)
[etcddb_client.go#L104-L121](https://github.com/arturgontijo/snet-daemon/blob/config/etcddb/etcddb_client.go#L104-L121)

**Comment by vsbogd** [comment]
@anandrgitnirman , do we have daemon release which includes this fix?
