### ISSUE TITLE
revert back state service changes in Proto on getting all channel state 

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-daemon#404]
refer to #402

**Comment by vsbogd** [comment]
@anandrgitnirman , what is the reason of reverting it ?

**Comment by anandrgitnirman** [comment]
So SDK wanted this functinality in Daemon , and we felt Daemon might be able to give a list of all channels if available ( with the latest state) .Advantages
All SDKs use this rather than building writing code to get all the channels from block chain
Daemon is one central place to get the state of the channel

While , the intent seemed fine , this also creates a potential risk if Daemon decides to be a bad actor for example not return all the channels ( skip the ones with a lot of funds still available) .. and force the client to thus add more funds to existing channel even when not required
