### ISSUE TITLE
Service provider doesn't have access to the channel state via PaymentChannelStateService

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#447]
If service provider tries to get latest channel state using `PaymentChannelStateService.GetChannelState` method it is rejected because it is not a signer nor sender of the channel. Nevertheless it has access to the similar data via `ProviderControlService` methods.

I would suggest fixing authentication code to allow service provider getting channel state via `PaymentChannelStateService` as well.

**Comment by anandrgitnirman** [comment]
just to be sure , the suggestion here is to check if the user making the request is from either of the below
signer of the channel **or** Sender of the Channel **or** Reciepeint Address(as defined in org metadata)

**Comment by vsbogd** [comment]
> signer of the channel or Sender of the Channel or Reciepeint Address(as defined in org metadata)

Yes
