### ISSUE TITLE
TestCompareWithLatestBlockNumber fails because Infura forbids access without project-id

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#448]
Test log (from https://circleci.com/gh/singnet/snet-daemon/670):
```
=== RUN   TestCompareWithLatestBlockNumber
time="2020-02-11T08:42:54Z" level=info msg="The Network specified is :ropsten, and maps to the Network Id 3, the determined Registry address is 0x663422c6999ff94933dbcb388623952cf2407f6f and block chain end point is https://ropsten.infura.io"
time="2020-02-11T08:42:54Z" level=info
time="2020-02-11T08:42:54Z" level=error msg="error determining current block" error="403 Forbidden {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32600,\"message\":\"project ID is required\",\"data\":{\"reason\":\"project ID not provided\",\"see\":\"https://infura.io/dashboard\"}}}"
--- FAIL: TestCompareWithLatestBlockNumber (0.21s)
```

**Comment by anandrgitnirman** [comment]
we now have a test project ID , the builds are fine now, so ok to close ?

**Comment by vsbogd** [comment]
Well, I thought about making build independent of external Ethereum network. One of the issues with current test implementation is that test cannot be executed offline. Separating authentication and getting current Ethereum block logic can improve performance. For example if `CurrentBlock` is called few times during short time period it could cache and return same value without getting it from Ethereum network twice. But it is a subject for another issue I believe.

**Comment by anandrgitnirman** [comment]
#429
