### ISSUE TITLE
Remove "passthrough_enabled" key

### ISSUE THREAD

**Issue by arturgontijo** [singnet/snet-daemon#467]
Is it possible to remove `"passthrough_enabled"`, eg:
```
"passthrough_enabled": true,
"passthrough_endpoint": "http://localhost:7003",
```
And stay only with the `"passthrough_endpoint"`?

**Comment by anandrgitnirman** [comment]
@arturgontijo we may have some merit in keeping this ( will be useful for just testing ) #487
