### ISSUE TITLE
Ability to Start Claims on Multiple Channels at the Same time 

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-daemon#476]
Currently we have the StartClaim for just a single Channel , we need to have an ability to StartClaims for multiple channels too,

Here is our use case to do it from publisher Portal 
The User makes a Daemon call to the get all the pending claims ( using metamask signature) 
The user then needs to call the start claim for every channel that he intends to claim ( thus a new signature again ) for every invocation od StartClaim !
PS You can make Multiple Claims in BlockChain in a single call multiChannelClaim

The Proposal here is to add a new RPC method **StartClaimsOnMultipleChannels** that takes a list of ChannelIds , What Daemon will do is invoke the StartClaim internally for every channel Id passed

```proto
rpc StartClaimForMultipleChannels(StartMultipleClaimRequest) returns (PaymentsListReply)  
message StartMultipleClaimRequest {
    //address of MultiPartyEscrow contract
    string mpe_address = 1;
    repeated bytes channel_id    = 2;
   uint64 current_block = 3;
    //signature will be as follows ( sequence is an ascending order of channel_ids)
    //("__StartClaimForMultipleChannels_, mpe_address,channel_id1,channel_id2,...,current_block_number)
    bytes signature = 4;
}

```
@astroseger @vsbogd @raamb ,will request you to please opine here

**Comment by vsbogd** [comment]
sure we can do it
