### ISSUE TITLE
redirect the logs generated by etcd to a file

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-daemon#520]
We have configured ETCD as a Linux Service.
Currently all the logs that is been generated by etcd are getting written to journalctl.
When configured to output the stderr & stdout to a file as a part of the service, it did not write to the file rather it continued writing journalctl.
Difficicult to set up alerts say on cloudwatch with the above described issue.

**Comment by vsbogd** [comment]
@anandrgitnirman , is it related to `snet-daemon` ? From description I see that it is about standalone `ETCD` which is not part of the daemon. In daemon all logs should be collected and rotated via `logrus` according rules which user wrote into configuration file.

If it is not about daemon, then I propose closing it and opening in correct repo.

**Comment by anandrgitnirman** [comment]
makes sense, it is a about  etcd, will raise it with them , just watned to keep a tracker at our end as only daemon relates to etcd now
