### ISSUE TITLE
Upgrade Go compiler version of Mac OS X cross compilation scripts to 1.15

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#529]
According https://github.com/singnet/snet-daemon/issues/201#issuecomment-475133084 we can increase `GO_VERSION` to 1.15 in ` scripts/build-xgo` and remove unnecessary patches after https://github.com/singnet/snet-daemon/pull/519 is merged.

**Comment by anandrgitnirman** [comment]
Error when we use 1.14 or higher 
Checking for required docker image karalabe/xgo-1.14.x... not found!

Checking for required docker image karalabe/xgo-1.13.x... found.
