### ISSUE TITLE
Publish state_service.proto in release artifacts

### ISSUE THREAD

**Issue by vsbogd** [singnet/snet-daemon#99]
```state_service.proto``` is used by snet-daemon client to get information about payment channels.
It is a part of snet-daemon API and it should be published in release artifacts.

**Comment by raamb** [comment]
@anandrgitnirman is this completed? Can we close the issue

**Comment by vsbogd** [comment]
@anandrgitnirman, I don't see `.proto` files in released artifacts? Could you please clarify which artifact do you mean?

**Comment by anandrgitnirman** [comment]
will share the details once done, will raise a PR for review  , this is work in progress

**Comment by vsbogd** [comment]
Ok, got it,  read it inaccurately first time

**Comment by anandrgitnirman** [comment]
all protos are now published as part of Daemon release [v0.1.10] (https://github.com/singnet/snet-daemon/releases/tag/v0.1.10) and any future releases  
you will find the files under the directory /proto

**Comment by vsbogd** [comment]
do we have a script to create release artifacts?

**Comment by raamb** [comment]
Yes, its an AWS code build. It also sets the version in the daemon before the build and tags the release in Github as well.

**Comment by vsbogd** [comment]
I think it makes sense to add this code into repo as well. Or may be it is already on github, but located in other repo?

**Comment by raamb** [comment]
Yes, this is part of the infrastructure repo which is private.

**Comment by vsbogd** [comment]
Any reason why this script cannot be added to this one?

**Comment by raamb** [comment]
No particular reason except that we wanted to keep all infra related scripts in one place rather than have it distributed across repos, easier to manage them.

**Comment by vsbogd** [comment]
Ah ok, may be it doesn't matter for now.
